apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app-aviral
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aviral31/demo-argocd.git
    targetRevision: HEAD
    path: k8s-manifest
  destination:
    server: https://kubernetes.default.svc
    namespace: aviral-k8
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - syncTimeout=30s
    - CreateNamespace=true
